<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE module [ 
<!-- Add the following to any file that is to be validated against this DTD:

<!DOCTYPE module PUBLIC
    "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
    "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">
-->

<!ELEMENT module (module|property|metadata|message)*>
<!ATTLIST module name NMTOKEN #REQUIRED>

<!ELEMENT property EMPTY>
<!ATTLIST property
  name NMTOKEN #REQUIRED
    value CDATA #REQUIRED
    default CDATA #IMPLIED
>

<!--

   Used to store metadata in the Checkstyle configuration file. This
   information is ignored by Checkstyle. This may be useful if you want to
   store plug-in specific information.

   To avoid name clashes between different tools/plug-ins you are *strongly*
   encouraged to prefix all names with your domain name. For example, use the
   name "com.mycompany.parameter" instead of "parameter".

   The prefix "com.puppycrawl." is reserved for Checkstyle.

-->

<!ELEMENT metadata EMPTY>
<!ATTLIST metadata
  name NMTOKEN #REQUIRED
  value CDATA #REQUIRED
>

<!--
   Can be used to replaced some generic Checkstyle messages with a custom
   messages.

   The 'key' attribute specifies for which actual Checkstyle message the
   replacing should occur, look into Checkstyles message.properties for
   the according message keys.

   The 'value' attribute defines the custom message patterns including
   message parameter placeholders as defined in the original Checkstyle
   messages (again see message.properties for reference).
-->
<!ELEMENT message EMPTY>
<!ATTLIST message
  key NMTOKEN #REQUIRED
  value CDATA #REQUIRED
>

]>

<!--
    Checkstyle-Configuration for Checkstyle 5: SB
    $Id: sb-checks.xml 36937 2010-04-08 08:49:57Z weinhold $
-->
<module name="Checker">
  <property name="severity" value="warning"/>
  <module name="TreeWalker">
    <module name="JavadocType">
      <property name="scope" value="protected"/>
    </module>
    <module name="LocalVariableName"/>
    <module name="MemberName">
      <property name="applyToProtected" value="false"/>
      <property name="applyToPrivate" value="false"/>
    </module>
    <module name="MethodName"/>
    <module name="PackageName"/>
    <module name="ParameterName"/>
    <module name="TypeName"/>
    <module name="JavadocVariable">
      <property name="scope" value="package"/>
    </module>
    <module name="JavadocStyle">
      <property name="scope" value="protected"/>
      <property name="checkEmptyJavadoc" value="true"/>
      <property name="checkFirstSentence" value="false"/>
    </module>
    <module name="MemberName">
      <property name="applyToPublic" value="false"/>
      <property name="applyToPackage" value="false"/>
      <property name="format" value="([\_][a-zA-Z]|[\__][a-zA-Z]|[a-z])[a-zA-Z0-9]*$"/>
    </module>
    <module name="IllegalImport"/>
    <module name="RedundantImport"/>
    <module name="UnusedImports"/>
    <module name="AnonInnerLength">
      <property name="max" value="100"/>
    </module>
    <module name="AnonInnerLength"/>
    <module name="MethodLength"/>
    <module name="ParameterNumber"/>
    <module name="ModifierOrder"/>
    <module name="NeedBraces"/>
    <module name="RightCurly">
      <property name="option" value="alone"/>
    </module>
    <module name="LeftCurly">
      <property name="option" value="nl"/>
    </module>
    <module name="EmptyBlock"/>
    <module name="EmptyForIteratorPad"/>
    <module name="NoWhitespaceAfter"/>
    <module name="NoWhitespaceBefore"/>
    <module name="MethodParamPad"/>
    <module name="ParenPad"/>
    <module name="TypecastParenPad">
      <property name="tokens" value="RPAREN,TYPECAST"/>
    </module>
    <module name="WhitespaceAfter"/>
    <module name="JavaNCSS">
      <property name="classMaximum" value="1000"/>
    </module>
    <module name="NPathComplexity"/>
    <module name="BooleanExpressionComplexity"/>
    <module name="AvoidInlineConditionals"/>
    <!--
      Removed in checkstyle 5.6 
      http://checkstyle.sourceforge.net/releasenotes.html
      <module name="DoubleCheckedLocking"/>  
    -->
    <module name="EmptyStatement"/>
    <module name="EqualsHashCode"/>
    <!-- RedundantThrows was removed with version 6.2 (see https://github.com/checkstyle/checkstyle/issues/473)
    <module name="RedundantThrows"/>
    -->
    <module name="MissingSwitchDefault"/>
    <module name="MagicNumber">
      <property name="severity" value="ignore"/>
    </module>
    <module name="SimplifyBooleanExpression"/>
    <module name="SimplifyBooleanReturn"/>
    <module name="StringLiteralEquality"/>
    <module name="SuperFinalize"/>
    <module name="TodoComment"/>
    <module name="ArrayTypeStyle"/>
    <module name="UpperEll"/>
    <module name="OperatorWrap"/>
    <module name="IllegalInstantiation"/>
    <module name="FinalClass"/>
    <module name="HideUtilityClassConstructor"/>
    <module name="InterfaceIsType"/>
    <module name="AvoidStarImport"/>
    <module name="CyclomaticComplexity">
      <property name="max" value="10"/>
    </module>
    <module name="NPathComplexity"/>
    <module name="VisibilityModifier"/>
    <module name="JavadocMethod">
      <property name="scope" value="public"/>
      <property name="allowMissingParamTags" value="true"/>
      <property name="allowMissingReturnTag" value="true"/>
    </module>
    <module name="MissingJavadocMethod">
      <property name="allowMissingPropertyJavadoc" value="true"/>
    </module>
    <module name="ConstantName">
      <property name="format" value="^[A-Z][A-Z0-9]*(_[A-Z0-9]+)*$|logger"/>
    </module>
    
  </module>
  <module name="LineLength">
    <property name="max" value="110"/>
    <property name="ignorePattern" value="^$|^import.*$|^ *\* *@version \$Id\:.*$"/>
  </module>
  <module name="FileTabCharacter" />
</module>
